# Generated by Django 5.0.9 on 2024-09-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pagevisits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.TextField(blank=True, null=True)),
                ('visit_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
